version: "3.8"

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  desafio-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - elasticsearch
    volumes:
      - .:/app

  desafio-3:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./desafio-3:/usr/share/nginx/html:ro
